name: on-gh-release
on:
  release:
    types: [published, unpublished, created, edited, deleted, prereleased, released]
    branches:
      - development

jobs:
  # one run
  one_run:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: 'asd'

  # update npm tags
  npm_tag_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - run: |
          npm config set registry https://registry.npmjs.org/
          npm config set _authToken=token
          npm dist-tag add ngx-bootstrap@${{ steps.package-version.outputs.current-version}} latest
